#!/bin/sh


if [ $# -ne 1 ]; then
	echo "arg1: path"
	exit
fi

if [ -f $1 ]; then
	echo "$1 is file."
	exit
fi

if [ ! -d $1 ]; then
	echo "$1 must be directory."
	exit
fi


GIT_LIST=`find $1 -name .git`

for GIT_PATH in $GIT_LIST
do
	CUR_PATH=${GIT_PATH%.git}
	GIT_OPTIONS="--git-dir=${GIT_PATH} --work-tree=${CUR_PATH}"

	GIT_DIFF=`git ${GIT_OPTIONS} diff`
	GIT_STATUS=`git ${GIT_OPTIONS} status`

	GIT_STATUS_UNTRACKED=`echo ${GIT_STATUS} | grep '# On branch master' | grep '# Untracked files:'`
	GIT_STATUS_PUSHED=`echo ${GIT_STATUS} | grep 'by [0-9] commit.'`
	GIT_STATUS_ADDED=`echo ${GIT_STATUS} | grep '# Changes to be committed:'`

	if [ "" = "$GIT_DIFF" -a "" = "$GIT_STATUS_UNTRACKED" -a "" = "$GIT_STATUS_PUSHED" -a "" = "$GIT_STATUS_ADDED" ]; then
		echo "OK $CUR_PATH"
	else
		echo "\033[31mNG $CUR_PATH\033[m"
	fi
done

